export interface Product {
  slug: string;
  name: string;
  tagline: string;
  price: number;
  image: string;
  category: "dev-humor" | "ai-culture" | "spicy";
  tags: string[];
  sizes: string[];
  colors: string[];
  featured?: boolean;
}

export const products: Product[] = [
  // ── DEV HUMOR ─────────────────────────────────────────
  {
    slug: "github-parody",
    name: "GitHub (Parody Logo)",
    tagline: "Where the world builds stolen code",
    price: 20,
    image: "/designs/github-parody.png",
    category: "dev-humor",
    tags: ["github", "parody", "code"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black", "Charcoal"],
    featured: true,
  },
  {
    slug: "bash-sleep-run",
    name: "$ bash $ sleep $ run",
    tagline: "The developer morning routine",
    price: 20,
    image: "/designs/bash-sleep-run.png",
    category: "dev-humor",
    tags: ["bash", "terminal", "linux"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "im-absolutely-right",
    name: "I'm Absolutely Right",
    tagline: "position: absolute; right: 0;",
    price: 20,
    image: "/designs/im-absolutely-right.png",
    category: "dev-humor",
    tags: ["css", "pun", "frontend"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black", "Navy"],
    featured: true,
  },
  {
    slug: "sudo-sandwich",
    name: "$ sudo make me a sandwich",
    tagline: "Okay.",
    price: 20,
    image: "/designs/sudo-sandwich.png",
    category: "dev-humor",
    tags: ["sudo", "linux", "classic"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
    featured: true,
  },
  {
    slug: "404-sleep",
    name: "404: Sleep Not Found",
    tagline: "Server error: body.rest() undefined",
    price: 20,
    image: "/designs/404-sleep.png",
    category: "dev-humor",
    tags: ["404", "sleep", "code"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "rm-rf-danger",
    name: "$ rm -rf /",
    tagline: "Living dangerously",
    price: 20,
    image: "/designs/rm-rf-danger.jpg",
    category: "dev-humor",
    tags: ["linux", "danger", "terminal"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black", "Red"],
  },
  {
    slug: "merge-no-conflicts",
    name: "I Merge Without Conflicts",
    tagline: "Said no one ever",
    price: 20,
    image: "/designs/merge-no-conflicts.jpg",
    category: "dev-humor",
    tags: ["git", "merge", "flex"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "no-dependencies",
    name: "This Shirt Has No Dependencies",
    tagline: "Unlike your node_modules",
    price: 20,
    image: "/designs/no-dependencies.jpg",
    category: "dev-humor",
    tags: ["npm", "dependencies", "node"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black", "Charcoal"],
  },
  {
    slug: "fuck-it-ship-it",
    name: "F*ck It, Ship It",
    tagline: "The official motto of Friday deploys",
    price: 20,
    image: "/designs/fuck-it-ship-it.jpg",
    category: "dev-humor",
    tags: ["ship", "deploy", "yolo"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
    featured: true,
  },
  {
    slug: "im-loggin-it",
    name: "I'm Loggin' It",
    tagline: "console.log() everything",
    price: 20,
    image: "/designs/im-loggin-it.jpg",
    category: "dev-humor",
    tags: ["logging", "debug", "parody"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "terminal-illness",
    name: "Terminal Illness",
    tagline: "Diagnosed: chronic bash addiction",
    price: 20,
    image: "/designs/terminal-illness.jpg",
    category: "dev-humor",
    tags: ["terminal", "pun", "dark-humor"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "push-it",
    name: "Push It",
    tagline: "git push --force",
    price: 20,
    image: "/designs/push-it.jpg",
    category: "dev-humor",
    tags: ["git", "push", "force"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "fork-it",
    name: "Fork It",
    tagline: "When you can't fix it, fork it",
    price: 20,
    image: "/designs/fork-it.jpg",
    category: "dev-humor",
    tags: ["git", "fork", "humor"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "yolo-mode",
    name: "Running On YOLO Mode",
    tagline: "--no-verify --force",
    price: 20,
    image: "/designs/yolo-mode.jpg",
    category: "dev-humor",
    tags: ["yolo", "deploy", "reckless"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },

  // ── AI CULTURE ────────────────────────────────────────
  {
    slug: "got-tokens",
    name: "Got Tokens?",
    tagline: "Running low on context",
    price: 20,
    image: "/designs/got-tokens.jpg",
    category: "ai-culture",
    tags: ["tokens", "parody", "AI"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "sam-altman-owes-me",
    name: "Sam Altman Owes Me Money",
    tagline: "For all the free training data",
    price: 20,
    image: "/designs/sam-altman-owes-me.jpg",
    category: "ai-culture",
    tags: ["openai", "altman", "data"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
    featured: true,
  },
  {
    slug: "dangerously-skip-permissions",
    name: "Dangerously Skip Permissions",
    tagline: "--dangerouslyAllowAll",
    price: 20,
    image: "/designs/dangerously-skip-permissions.jpg",
    category: "ai-culture",
    tags: ["permissions", "security", "yolo"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
    featured: true,
  },
  {
    slug: "only-bots",
    name: "OnlyBots",
    tagline: "Exclusive AI content",
    price: 20,
    image: "/designs/only-bots.jpg",
    category: "ai-culture",
    tags: ["bots", "parody", "AI"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "fine-tuned-mom",
    name: "I Fine-Tuned Your Mom",
    tagline: "LoRA weight: yo_mama.safetensors",
    price: 20,
    image: "/designs/fine-tuned-mom.jpg",
    category: "ai-culture",
    tags: ["finetune", "roast", "AI"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "trained-deez-nuts",
    name: "Trained On Deez Nuts",
    tagline: "Dataset: deez_nuts_v2.jsonl",
    price: 20,
    image: "/designs/trained-deez-nuts.jpg",
    category: "ai-culture",
    tags: ["training", "roast", "AI"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },

  // ── SPICY ─────────────────────────────────────────────
  {
    slug: "got-root",
    name: "Got Root?",
    tagline: "# sudo -s",
    price: 20,
    image: "/designs/got-root.jpg",
    category: "spicy",
    tags: ["root", "sudo", "innuendo"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
    featured: true,
  },
  {
    slug: "show-me-backend",
    name: "Show Me Your Backend",
    tagline: "REST API preferred",
    price: 20,
    image: "/designs/show-me-backend.jpg",
    category: "spicy",
    tags: ["backend", "API", "innuendo"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "safe-word-ctrl-c",
    name: "My Safe Word Is Ctrl+C",
    tagline: "^C ^C ^C ^C ^C",
    price: 20,
    image: "/designs/safe-word-ctrl-c.jpg",
    category: "spicy",
    tags: ["ctrl-c", "safe-word", "innuendo"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "penetration-tested",
    name: "Fully Penetration Tested",
    tagline: "Certified secure",
    price: 20,
    image: "/designs/penetration-tested.jpg",
    category: "spicy",
    tags: ["pentest", "security", "innuendo"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "gpu-hotter-girlfriend",
    name: "My GPU Is Hotter Than Your Girlfriend",
    tagline: "Thermal throttling at 95°C",
    price: 20,
    image: "/designs/gpu-hotter-girlfriend.jpg",
    category: "spicy",
    tags: ["GPU", "roast", "hardware"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "wanna-see-my-vps",
    name: "Wanna See My VPS?",
    tagline: "16GB RAM, 4 cores, all night",
    price: 20,
    image: "/designs/wanna-see-my-vps.jpg",
    category: "spicy",
    tags: ["VPS", "server", "innuendo"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "dtf-down-to-fork",
    name: "DTF (Down To Fork)",
    tagline: "git fork --yes",
    price: 20,
    image: "/designs/dtf-down-to-fork.jpg",
    category: "spicy",
    tags: ["fork", "git", "innuendo"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
  {
    slug: "only-commit-git",
    name: "I Only Commit With Git",
    tagline: "Not ready for anything else",
    price: 20,
    image: "/designs/only-commit-git.jpg",
    category: "spicy",
    tags: ["commit", "git", "relationships"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Black"],
  },
];

export const categories = [
  { slug: "all", name: "All Designs", count: products.length },
  { slug: "dev-humor", name: "Dev Humor", count: products.filter(p => p.category === "dev-humor").length },
  { slug: "ai-culture", name: "AI Culture", count: products.filter(p => p.category === "ai-culture").length },
  { slug: "spicy", name: "Spicy", count: products.filter(p => p.category === "spicy").length },
];

export function getProduct(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.featured);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products;
  return products.filter(p => p.category === category);
}
